replicaCount: 1

# Image in my local registry
image: scolish-turbo-application-ui-website-server

service:
  name: website
  internalPort: 3000
  externalPort: 3000

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
