apiVersion: api/autoscalarv2
kind: HorizontalPodAutoscaler
metadata:
    name: {{ include "website.fullname" }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "website.fullname" }}
    minReplicas: 1
    maxReplicas: 3
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    behavior:
        scaleDown:
            stabilizationWindowSeconds: 300
            policies:
            - type: Percent
              value: 20
        scaleUp:
            stabilizationWindowSeconds: 300
            policies:
            - type: Percent
              value: 20
