apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ include "backbone.fullname" . }}
    labels:
        chart: {{ include "backbone.fullname" . }}
        app: {{ include "backbone.fullname" . }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "backbone.fullname" . }}
    minReplicas: 1
    maxReplicas: 3
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80    
    behavior:
        scaleDown:
            stabilizationWindowSeconds: 300
            policies:
            - type: Percent
              value: 20
        scaleUp:
            stabilizationWindowSeconds: 300
            policies:
            - type: Percent
              value: 20