replicaCount: 1
image: scolish-backbone-server # This image is on my local docker registry

service:
  name: backbone
  internalPort: 8080
  externalPort: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
